### ISSUE TITLE
Not able to select state according to selected country

### ISSUE THREAD

**Issue by dinshawraje** [arvindvyas/Country-State-Select#18]
Hi I am using gem and I had done 

<%= f.select :country, CountryStateSelect::Constant::COUNTRIES, {}, id: 'country_id' %>
so it shows me all the country list. Now I want when I select country then in other drop-down it will show list of all states. 
When i write this then also nothing happens. It does not populate states.
 <%= f.text_field :state_name ,:id=> 'state_name'%>

**Comment by arvindvyas** [comment]
@dinshawraje  have you added 
    //= require country_state_select
in application.js file
