### ISSUE TITLE
Add Integration tests and test for multiple instances of the country / state select

### ISSUE THREAD

**Issue by aldefouw** [arvindvyas/Country-State-Select#22]
We should write some integration tests for the JavaScript using cucumber.

The other thing we should test for is for multiple instances of the drop downs to make sure they aren't interfering with each other.

**Comment by aldefouw** [comment]
I have written some cucumber tests, but I am working on getting them working with Travis CI.  I will let you know when they are working.

**Comment by arvindvyas** [comment]
Great , I am planing for release 3.0.0 at 30th Oct let me know if we can add any other thing on it

**Comment by aldefouw** [comment]
Having some trouble with the Sauce Labs integration.  Do you have any experience with that?

**Comment by arvindvyas** [comment]
@aldefouw I have not work on it

**Comment by Faisal-nfl** [comment]
How to use multiple dropdowns on one page?
