### ISSUE TITLE
Version Note

### ISSUE THREAD

**Issue by aldefouw** [arvindvyas/Country-State-Select#26]
Hi Arvind - 

Great work on adding the Cities to the gem.  Looks great.  I might do a few pull requests in the future to clean up a few things that I noticed, but it looks really great overall.  

I was wondering if we need to create a git tag for version 3.0.  I see that versioning stops at 2.0.0 in git.  Rubygems appears to use the git tags to show releases.

If we want to follow Semantic versioning, which I think is a good idea, we should follow this guide:
http://semver.org/

That would put the gem at version 3.0.x because we have completely changed the public interface.  We should also change the version file in the gem itselt each time we cut a new release.

I think we should probably update the version to be like 3.0.x and do a git tag to reflect it.
 
Thoughts? 

Thanks,
Adam D.

**Comment by arvindvyas** [comment]
Hi Adam D

I have also found the same you mention , in this week we are going to release 3.0.0 , with tag as you suggested , also before that need to check all the functionality which I am doing , Also I have added couple of ticket like one demo app and wikki updation once it will done then I think we can go with new release. Thanks for share your thought.

Thanks 
Arvind
