### ISSUE TITLE
Problems with City selection

### ISSUE THREAD

**Issue by aldefouw** [arvindvyas/Country-State-Select#28]
- When you select a new country or state, the city field should really be reset.  It doesn't appear to do that right now.

- Also need to create a #city_options public method where it can gather a collection based upon the state selection, similar to what the #state_options method does right now.

Still need to fix the tests and dummy application as well.

**Comment by arvindvyas** [comment]
@aldefouw can you have a look in to it.

**Comment by aldefouw** [comment]
Hi Arvind.  I've been really busy with a project at work that's on deadline.  Late January I will be able to look at this stuff again.

**Comment by arvindvyas** [comment]
np @aldefouw I have fix that and published it , I am thinking what else I can add on it or enhance it . if you have any suggestion please create a issue thanks
