### ISSUE TITLE
JavaScript: CountryStateSelect is not defined

### ISSUE THREAD

**Issue by loganh0522** [arvindvyas/Country-State-Select#31]
Hello, 
I would like to start by saying thank you for developing a gem with this functionality. I have followed the process to integrate your Gem, however, my app does not recognize the CountryStateSelect function in JavaScript. 

I could not find much documentation, any help resolving this issue would be appreciated.

**Comment by variousred** [comment]
Getting this as well.

**Comment by variousred** [comment]
I assume its because i'm not loading the script in with the `  //= require chosen-jquery`. The documentation implies that using `chosen rails` is optional, but only explains how to require for that scenario.

**Comment by variousred** [comment]
logan, for the mean time i've done this
```<%= javascript_include_tag "country_state_select" %>
<%= javascript_tag do %>
$(document).on('ready page:load', function() {
  return CountryStateSelect({
    country_id: "country",
    state_id: "state"
  });
});
```

**Comment by loganh0522** [comment]
@variousred Thanks for that, Ill try that out!

**Comment by variousred** [comment]
@loganh0522 anywhere, really. I had it at the top of my form partial file.

**Comment by arvindvyas** [comment]
@loganh0522 if you have seen gem then if you will go inside test/dummy  there is demo app in which you can see how this application is working, let me know if you still have problem?
