### ISSUE TITLE
chosenIsRequired function

### ISSUE THREAD

**Issue by variousred** [arvindvyas/Country-State-Select#32]
For people who are NOT using chosen:

I could not get this to work unless i modified these sections

```
  function addChosenToState(){
    if (chosenIsRequired && stateIsNotText()) {
      $('#' + state_id).chosen();
    }
  }

```
to this
```
  function addChosenToState(){
    if (chosenIsRequired() && stateIsNotText()) {
      $('#' + state_id).chosen();
    }
  }
```
(the `chosenIsRequired` as a function call)
in https://github.com/arvindvyas/Country-State-Select/blob/master/vendor/assets/javascript/country_state_select.js.erb

**Comment by arvindvyas** [comment]
@variousred thinks I am looking into it .

**Comment by variousred** [comment]
Thanks @arvindvyas
