### ISSUE TITLE
Compass outdated dependency problem

### ISSUE THREAD

**Issue by Bandes** [arvindvyas/Country-State-Select#47]
The latest build appears to depend on `compass-rails (~> 2.0.4)` which is badly outdated and won't install on my Rails 5 application. Is it possible to update the dependency?

**Comment by aldefouw** [comment]
These are the dependencies that I see in the gemspec:

`  spec.add_development_dependency "bundler", "~> 1.6"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "rspec"
  spec.add_development_dependency 'pry'

  spec.add_runtime_dependency 'rails'
spec.add_runtime_dependency 'city-state'`

Where are you seeing a compass-rails dependency?

**Comment by Bandes** [comment]
I get the following errors when I include

`gem 'country_state_select', '~> 3.0.2'` 

```
Bundler could not find compatible versions for gem "sass-rails":
  In snapshot (Gemfile.lock):
    sass-rails (= 5.0.6)

  In Gemfile:
    sass-rails (~> 5.0)

    country_state_select (~> 3.0.2) was resolved to 3.0.2, which depends on
      compass-rails (~> 2.0.4) was resolved to 2.0.4, which depends on
        sass-rails (<= 5.0.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "sprockets":
  In snapshot (Gemfile.lock):
    sprockets (= 3.7.1)

  In Gemfile:
    country_state_select (~> 3.0.2) was resolved to 3.0.2, which depends on
      compass-rails (~> 2.0.4) was resolved to 2.0.5, which depends on
        sprockets (< 2.13)

    sass-rails (~> 5.0) was resolved to 5.0.6, which depends on
      sprockets (< 4.0, >= 2.8)

    country_state_select (~> 3.0.2) was resolved to 3.0.2, which depends on
      rails was resolved to 5.0.1, which depends on
        sprockets-rails (>= 2.0.0) was resolved to 3.2.0, which depends on
          sprockets (>= 3.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

```

At the moment I am using the fork from @aldefouw (git: 'https://github.com/aldefouw/Country-State-Select.git', branch: 'alcd-development') in order to get around this problem, but I would prefer to use an official release if this can be fixed.

**Comment by joemsak** [comment]
I get the same problem trying to use 3.0 in rails 5. In fact, it sparked a bug report on bundler itself, because in my case the resolver did not tell me the problem was with this gem

Issue: https://github.com/bundler/bundler/issues/5569

Comment where I try to update to 3.0.2 https://github.com/bundler/bundler/issues/5569#issuecomment-292818503

**Comment by joemsak** [comment]
If I take the resolver's install of 2.0, I can run bundle install, but then I can't run `rails app:update`

```
Bundler::GemRequireError: There was an error while trying to load the gem 'country_state_select'.
Gem Load Error is: Unsupported rails version
```

**Comment by joemsak** [comment]
Just wanna let you know using the master branch off of github seems to have worked. I was able to run `rails app:update` without trouble from this gem

**Comment by arvindvyas** [comment]
will remove all the dependencies in the latest release

**Comment by arvindvyas** [comment]
removed in latest release
