### ISSUE TITLE
javascript isnt working on rails 5

### ISSUE THREAD

**Issue by eperezgarcia1201** [arvindvyas/Country-State-Select#49]
Im using rails 5 and when i select my country i would like to get the cities of the selected country but i cant do it... i tried it in many ways already and nothing is working properly
thanks

**Comment by RailsCod3rFuture** [comment]
I'm getting Uncaught ReferenceError: CountrySelect is not defined.

**Comment by Qwertie-** [comment]
@RailsCod3rFuture Try adding `//= require country_state_select` to application.js

**Comment by RailsCod3rFuture** [comment]
@Qwertie- It's working now, thanks!
