### ISSUE TITLE
Provinces missing?

### ISSUE THREAD

**Issue by ryan2johnson9** [arvindvyas/Country-State-Select#50]
Hi, I see in the Readme a lot of references to  "State / Province". So I thought this gem would provide provinces. But it does not seem to unless I am missing something? (I realise there seem to be differing interpretations of the word Province so it is understandable - e.g. Canada's states are referred to as Provinces)

Spain for example has 17 Autonomous Regions or States(e.g. Catalonia), 50 Provinces (e.g. Barcelona (also a city) - these seem to have the same name as the major city in the Province) and lots more cities. Apparently the provinces are more meaningful for the Spanish but I cannot seem to find them in your gem.

Is there some method for doing this or does it not exist?

**Comment by arvindvyas** [comment]
@ryan2johnson9 can you check The data for Countries and States is populated by the excellent city-state gem. for more details

**Comment by ryan2johnson9** [comment]
Ahh.. woops, we are using country_select,  not this gem, sorry, maybe we should use this one instead...
