### ISSUE TITLE
possibility to update to rails 5?

### ISSUE THREAD

**Issue by dcalixto** [arvindvyas/Country-State-Select#51]
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.1.2)

  In Gemfile:
    rails

    country_state_select was resolved to 2.0.0, which depends on
      rails (>= 3.0)

**Comment by dsounded** [comment]
Yeah, code is already in master. but no new version:

https://github.com/arvindvyas/Country-State-Select/commit/df934e2b345cc962c77aeb50184c4874f975cb61#diff-18aa0f96689019e8dd5124f9f5e89edc

it can be used like this temporary:

`gem 'country_state_select', git: 'git://github.com/arvindvyas/Country-State-Select', branch: :master`

**Comment by aristizabal95** [comment]
@dsounded after changing the Gemfile for your solution, received this error:

`git://github.com/arvindvyas/Country-State-Select (at master@df934e2) is not yet checked out. Run `bundle install` first.`

had to solve it by running this:

`bundle install --deployment`

which is by no means a good solution. Yet I'm able to work with this gem for now. Would be nice if it got updated to fully work with rails 5 though.

In case anyone is going to use the code above, you can undo it later by running this

`bundle install --no-deployment`

src: https://stackoverflow.com/questions/6648870/is-not-checked-out-bundle-install-does-not-fix-help#comment45219008_6648894

**Comment by RailsCod3rFuture** [comment]
Has anyone created a repo to update the gemspec???

**Comment by arvindvyas** [comment]
thanks guys looking into it will be updating it

**Comment by arvindvyas** [comment]
master is live now
