### ISSUE TITLE
How to save country, state or city name instead of code?

### ISSUE THREAD

**Issue by b3ccio** [arvindvyas/Country-State-Select#58]
This is probably an obvious question, but I don't see it in the readme. How would I save a country's name instead of the code? It seems to only allow an `_id`.

**Comment by arvindvyas** [comment]
It's not good to save direct country name due to conflict issue but if you still want those you can use a pre-define method which is already in this gem and make your own select 

```
CountryStateSelect.countries_collection
CountryStateSelect.states_collection(f, options)
```
